variable "project_name" {
  type        = string
  default     = "hanoitrip"
  description = "Short resource name prefix."
}

variable "environment" {
  type        = string
  default     = "dev"
  description = "Environment suffix."
  validation {
    condition     = contains(["dev", "test", "prod"], var.environment)
    error_message = "Use dev, test, or prod."
  }
}

variable "location" {
  type        = string
  default     = "eastasia"
  description = "Azure region."
}

variable "allowed_ip_cidrs" {
  type        = list(string)
  description = "Public CIDRs allowed to access production and staging."
  validation {
    condition     = length(var.allowed_ip_cidrs) > 0 && alltrue([for cidr in var.allowed_ip_cidrs : can(cidrhost(cidr, 0))])
    error_message = "Provide at least one valid CIDR, normally your current public IP as /32."
  }
}

variable "vnet_address_space" {
  type        = list(string)
  default     = ["10.20.0.0/16"]
  description = "Address space for App Service outbound integration."

  validation {
    condition     = length(var.vnet_address_space) > 0 && alltrue([for cidr in var.vnet_address_space : can(cidrhost(cidr, 0))])
    error_message = "Provide at least one valid VNet CIDR."
  }
}

variable "app_subnet_address_prefixes" {
  type        = list(string)
  default     = ["10.20.1.0/24"]
  description = "Dedicated delegated subnet used by production and staging for Key Vault access."

  validation {
    condition     = length(var.app_subnet_address_prefixes) > 0 && alltrue([for cidr in var.app_subnet_address_prefixes : can(cidrhost(cidr, 0))])
    error_message = "Provide at least one valid subnet CIDR."
  }
}

variable "mysql_app_outbound_ips" {
  type        = set(string)
  default     = []
  description = "App Service outbound IPv4 addresses allowed through the MySQL firewall. Generated by scripts/terraform/apply-app.sh after the first apply."

  validation {
    condition = alltrue([
      for ip in var.mysql_app_outbound_ips : !strcontains(ip, "/") && can(cidrhost("${ip}/32", 0))
    ])
    error_message = "Use bare IPv4 addresses without CIDR suffixes."
  }
}

variable "bootstrap_image_repository" {
  type        = string
  default     = "hanoitrip"
  description = "Repository created in the new ACR for the first runnable application image."
  validation {
    condition     = can(regex("^[a-z0-9]+(?:[._/-][a-z0-9]+)*$", var.bootstrap_image_repository))
    error_message = "Use a lowercase OCI repository name."
  }
}

variable "routes_mode" {
  type        = string
  default     = "demo"
  description = "Use demo until Google keys have been placed in Key Vault."
  validation {
    condition     = contains(["demo", "google"], var.routes_mode)
    error_message = "Use demo or google."
  }
}

variable "road_provider" {
  type        = string
  default     = "disabled"
  description = "Enable VIETMAP road/search only after the server key exists in Key Vault."
  validation {
    condition     = contains(["disabled", "vietmap"], var.road_provider)
    error_message = "Use disabled or vietmap."
  }
}

variable "mysql_sku_name" {
  type        = string
  default     = "B_Standard_B1ms"
  description = "Small sandbox MySQL SKU; verify availability in the selected region."
}

variable "app_service_sku" {
  type        = string
  default     = "S1"
  description = "Standard is the minimum intended tier for deployment slots and autoscale."
}

variable "alert_email" {
  type        = string
  description = "Email receiver for Azure Monitor alerts."
}

variable "mysql_secret_expiration_date" {
  type        = string
  description = "RFC 3339 expiry for the generated MySQL administrator secret; rotate the password before this date."

  validation {
    condition     = can(formatdate("YYYY-MM-DD'T'hh:mm:ssZ", var.mysql_secret_expiration_date))
    error_message = "Use an RFC 3339 timestamp such as 2027-12-31T23:59:59Z."
  }
}

variable "github_actions_principal_object_id" {
  type        = string
  default     = null
  nullable    = true
  description = "Object ID of the GitHub OIDC service principal; optional until OIDC is created."
}

variable "tags" {
  type = map(string)
  default = {
    project     = "hanoitrip"
    environment = "sandbox"
    managed_by  = "terraform"
  }
}
